### ISSUE TITLE
[NEW FEATURE] Allow no location

### ISSUE THREAD

**Issue by AntoinePiron** [org-SCAN/react-app#8]
**Description of the desired solution**
Allow the user to use the application without location permission

**Tasks to succed**

- [ ] Don't block when launching the app without location
- [ ] Don't block taking photos
- [ ] If a location takes more than 5 seconds when taking a photo, ignore it
